baseURL = 'https://www.blockwirenews.com/'
languageCode = 'en-us'
title = 'BlockWireNews - Real-Time Cryptocurrency News & Market Analysis'
# theme = 'ananke'  # Removed theme to use custom templates

# URL Settings
canonifyURLs = true
relativeURLs = false

# Pagination Settings
[pagination]
  pagerSize = 12

# Enable robots.txt
enableRobotsTXT = true

# Enable sitemap
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  blog = "/blog/:slug/"
  news = "/news/:slug/"
  bitcoin-news = "/bitcoin-news/:slug/"
  ethereum-news = "/ethereum-news/:slug/"
  defi-news = "/defi-news/:slug/"
  nft-news = "/nft-news/:slug/"
  pages = "/:slug/"
  categories = "/categories/:slug/"
  tags = "/topics/:slug/"
  authors = "/author/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  topic = "topics"

[params]
  description = "Get real-time cryptocurrency news, Bitcoin price analysis, Ethereum updates, DeFi insights, and NFT market trends. Your trusted source for blockchain and crypto news."
  images = ["https://www.blockwirenews.com/og-image.jpg"]
  title = "BlockWireNews - Cryptocurrency News Aggregator"
  favicon = "/favicon.ico"
  site_logo = "/logo.png"
  twitter_cards = true
  
  # Ananke theme specific - disable custom CSS compilation
  ananke_socials = []
  custom_css = []
  disable_theme_css = false
  
  # Social Media
  twitter = "https://twitter.com/blockwirenews"
  facebook = "https://facebook.com/blockwirenews"
  instagram = "https://instagram.com/blockwirenews"
  youtube = "https://youtube.com/blockwirenews"
  
  # Google Analytics
  google_analytics_id = "G-XXXXXXXXXX"
  
  # AdSense
  google_adsense_id = "ca-pub-5523870768931777"

# Main Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Bitcoin"
  url = "/bitcoin-news/"
  weight = 3

[[menu.main]]
  name = "Ethereum"
  url = "/ethereum-news/"
  weight = 4

[[menu.main]]
  name = "DeFi"
  url = "/defi-news/"
  weight = 5

[[menu.main]]
  name = "NFTs"
  url = "/nft-news/"
  weight = 6

[[menu.main]]
  name = "Analysis"
  url = "/market-analysis/"
  weight = 7

[[menu.main]]
  name = "All News"
  url = "/all-news/"
  weight = 8

# Footer Menu
[[menu.footer]]
  name = "About Us"
  url = "/about/"
  weight = 1

[[menu.footer]]
  name = "Contact"
  url = "/contact/"
  weight = 2

[[menu.footer]]
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 3

[[menu.footer]]
  name = "Terms of Service"
  url = "/terms-of-service/"
  weight = 4

[[menu.footer]]
  name = "Advertise"
  url = "/advertise/"
  weight = 5

# Output formats for different content types
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# RSS Feed settings
[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"

# JSON Feed for API
[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

# Markdown settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

# Security settings
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^git$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

# Language settings
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      description = "Real-time cryptocurrency news aggregator"

# Related content settings
[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "categories"
    weight = 60
  [[related.indices]]
    name = "date"
    weight = 10

# Privacy settings (GDPR compliance)
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.x]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

# Build settings
[build]
  noJSConfigInAssets = true
  useResourceCacheWhen = 'fallback'
  writeStats = false
  
# Module settings (if using Hugo Modules)
[module]
  [module.hugoVersion]
    min = "0.112.0"