baseURL = 'https://www.blockwirenews.com'
languageCode = 'en-us'
title = 'BlockWireNews - Aggregated CryptoCurrency News'
theme = 'ananke'
enableRobotsTXT = true
sitemap:
  changefreq: "hourly"
  priority: 0.5
  filename: "sitemap.xml"
