[build]
  command   = "hugo"
  publish   = "public"
  # Tell Netlify not to run npm install
  ignore = "false"

[context.production.environment]
  HUGO_VERSION = "0.114.3"    # or whatever Hugo version you’re using
  HUGO_ENV     = "production"
  # Prevent Netlify from running 'npm install' by pointing at an empty install
  NPM_FLAGS    = "--ignore-scripts"