[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.148.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/tags/*"
  to = "/topics/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/bitcoin"
  to = "/bitcoin-news/"
  status = 301
  force = true

[[redirects]]
  from = "/ethereum"
  to = "/ethereum-news/"
  status = 301
  force = true

[[redirects]]
  from = "/defi"
  to = "/defi-news/"
  status = 301
  force = true

[[redirects]]
  from = "/nft"
  to = "/nft-news/"
  status = 301
  force = true