name: Update Crypto JSON

# Run once an hour (every ‘0’ minute of every hour). Adjust as needed.
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  # allows you to trigger this manually from the Actions tab

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # persist-credentials:true lets us push back using the automatically-provided GITHUB_TOKEN
          persist-credentials: true

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install any Python dependencies your scraper needs
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedparser

      # 4) Run the scraper (this should overwrite data/crypto.json)
      - name: Run cricket scraper
        run: python scrape.py

      # 5) Commit & push any change to data/crypto.json
      - name: Commit updated JSON
        id: commit_changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "chore: automated update of data/crypto.json"
          add: 'data/crypto.json'

      # 6) (Optional) Print a note if nothing changed
      - name: Notify if no changes
        if: steps.commit_changes.outputs.committed == 'false'
        run: echo "No changes in data/crypto.json; nothing to commit."
