name: Update Crypto JSON

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: [self-hosted, linux]

    steps:
      - name: Check out repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0            # ensure full history for rebasing
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedparser

      - name: Pull latest main and rebase
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Run scraper
        run: python scrape.py

      - name: Commit updated JSON
        id: commit_changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "chore: automated update of data/crypto.json"
          add: 'data/crypto.json'

      - name: Push changes
        if: steps.commit_changes.outputs.committed == 'true'
        run: git push origin main
